// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC31yNKZ96rUwH7uTLcXHI63s_0W-6ejzE',
    appId: '1:640041135404:web:74af29f168a6ca07e15089',
    messagingSenderId: '640041135404',
    projectId: 'pserv-be-ch4r',
    authDomain: 'pserv-be-ch4r.firebaseapp.com',
    storageBucket: 'pserv-be-ch4r.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIxDnCLcA7PwzyhC6px0s5IStupoLwh4',
    appId: '1:640041135404:android:12f42e70a0831f57e15089',
    messagingSenderId: '640041135404',
    projectId: 'pserv-be-ch4r',
    storageBucket: 'pserv-be-ch4r.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC24WLJv8PCK-lqvD4Bl5RIjT6muIEU5Ig',
    appId: '1:640041135404:ios:e228239653fbfb1ee15089',
    messagingSenderId: '640041135404',
    projectId: 'pserv-be-ch4r',
    storageBucket: 'pserv-be-ch4r.appspot.com',
    iosBundleId: 'com.example.parkingDetectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC24WLJv8PCK-lqvD4Bl5RIjT6muIEU5Ig',
    appId: '1:640041135404:ios:4c2f54426e3ce3aee15089',
    messagingSenderId: '640041135404',
    projectId: 'pserv-be-ch4r',
    storageBucket: 'pserv-be-ch4r.appspot.com',
    iosBundleId: 'com.example.parkingDetectorApp.RunnerTests',
  );
}
